-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.groups
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT chats_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.groups
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.groups
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.groups TO anon;

GRANT ALL ON TABLE public.groups TO postgres;

GRANT ALL ON TABLE public.groups TO supabase_admin;

GRANT ALL ON TABLE public.groups TO authenticated;

GRANT ALL ON TABLE public.groups TO service_role;

CREATE TABLE IF NOT EXISTS public.group_members
(
    group_id character varying COLLATE pg_catalog."default" NOT NULL,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id character varying COLLATE pg_catalog."default" NOT NULL,
    display_name character varying COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    picture_url text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    birthday date,
    CONSTRAINT group_members_pkey PRIMARY KEY (group_id, user_id),
    CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id)
        REFERENCES public.groups (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.group_members
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.group_members
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.group_members TO anon;

GRANT ALL ON TABLE public.group_members TO postgres;

GRANT ALL ON TABLE public.group_members TO supabase_admin;

GRANT ALL ON TABLE public.group_members TO authenticated;

GRANT ALL ON TABLE public.group_members TO service_role;

DROP TABLE IF EXISTS public.chats CASCADE;

DROP TABLE IF EXISTS public.chat_members CASCADE;
